spring:
  jpa:
    hibernate:
      ddl-auto: create-drop #create and drop schema
      #    可选参数
      #    create 启动时删数据库中的表，然后创建，退出时不删除数据表
      #    create-drop 启动时删数据库中的表，然后创建，退出时删除数据表 如果表不存在报错
      #    update 如果启动时表格式不一致则更新表，原有数据保留
      #    validate 项目启动表结构进行校验 如果不一致则报错
    properties:
      hibernate:
        format_sql: true
        show_sql: true

management:
  endpoint:
    flowable:
      enabled: true
  endpoints:
    web:
      exposure:
        include: '*'